---
# Ansible job to make a jenkins CentOS 7 build server.

- hosts: main
  tasks:

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
    tags:
      - upgrade
      - patch

#######################################
##                                   ##
## Install devel and build packages  ##
##                                   ##
#######################################

  - name: install git
    yum:
      name: 'git'
      state: latest

  - name: install dev packages
    yum:
      name: 'rpmdevtools'
      state: latest

  - name: install gcc
    yum:
      name: 'gcc'
      state: latest

  - name: install make
    yum:
      name:  'make'
      state: latest

  - name: install automake
    yum:
      name: 'automake'
      state: latest

  - name: install autconf
    yum:
      name: 'autoconf'
      state: latest

  - name: install rpm-build
    yum:
      name: 'rpm-build'
      state: latest

  - name: install xmlto
    yum:
      name: 'xmlto'
      state: latest

  - name: install zlib-devel
    yum:
      name: 'zlib-devel'
      state: latest

  - name: install libselinux-devel
    yum:
      name: 'libselinux-devel'
      state: latest

  - name: install lua-devel
    yum:
      name: 'lua-devel'
      state: latest

  - name: install apr-devel
    yum:
      name: 'apr-devel'
      state: latest

  - name: install apr-util-devel
    yum:
      name: 'apr-util-devel'
      state: latest

  - name: install pcre-devel
    yum:
      name: 'pcre-devel'
      state: latest

  - name: install systemd-devel
    yum:
      name: 'systemd-devel'
      state: latest

  - name: install openssl-devel
    yum:
      name: 'openssl-devel'
      state: latest

  - name: install libxml2-devel
    yum:
      name: 'libxml2-devel'
      state: latest

  - name: install java-devel
    yum:
      name: 'java-devel'
      state: latest
    tags:
    - java-devel

  - name: install wget
    yum:
      name: 'wget'
      state: latest
    tags:
    - wget


##########################################
##                                      ##
#                                        #
#         Local configure.               #
#                                        #
##                                      ##
##########################################

  - name: setup build dir
    shell: mkdir -p /srv/build/ 2>/dev/null

  - name: enable firewall
    shell: systemctl enable firewalld || yum install -y firewalld && systemctl enable firewalld

  - name: allow 8080 on the local firewall
    shell: firewall-cmd --zone=public --add-port=8080/tcp --permanent

  - name: allow 22 on the local firewall
    shell: firewall-cmd --zone=public --add-port=22/tcp --permanent

  - name: reload the firewall
    shell: firewall-cmd --reload
    tags:
    - firewallReload

  - name: send over rpmmacros
    copy:
      src: .rpmmacros
      dest: /root/.rpmmacros
      owner: root
      group: root
      mode: '0644'
    tags:
    - macros



##########################################
##                                      ##
#                                        #
#         Install jenkins.               #
#                                        #
##                                      ##
##########################################

  - name: pull down jenkins repo file and instal the gpg key
    shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo && rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    tags:
    - jenkinsRepo
    - repo

  - name: install yum updates
    yum:
      name: '*'
      state: latest
    tags:
    - jenkinsInstall

  - name: install jenkins
    yum:
      name: 'jenkins'
      state: latest
    tags:
    - jenkinsInstall
    - patch
    - upgrade

  - name: restart jenkins
    shell: systemctl restart jenkins
    tags:
    - jenkinsInstall
    - patch
    - upgrade

  - name: remove docker
    shell: yum remove -y docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine
    tags:
    - rmDocker


  - name: install yum-utils
    yum:
      name: 'yum-utils'
      state: latest
    tags:
    - yumUtils
    - yum

  - name: install docker-ce.repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    tags:
    - docker
    - repo

  - name: install docker-ce
    yum:
      name: 'docker-ce.x86_64'
      state: latest
    tags:
    - docker
    - yum

  - name: restart docker
    shell: systemctl restart docker
    tags:
    - docker
    - dockerRestart

...
